# Generated by Django 3.2.19 on 2023-06-23 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 14, 33, 53, 21965, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
