# Generated by Django 3.2.19 on 2023-06-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservation_date'),
    ]

    operations = [
    ]
