# Generated by Django 3.2.19 on 2023-06-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20230623_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='capacity',
            new_name='guests',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_phone_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.AddField(
            model_name='table',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.table')),
            ],
        ),
    ]
