# Generated by Django 3.2.19 on 2023-06-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20230626_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ordered_items',
            field=models.ManyToManyField(blank=True, null=True, to='reservations.Item'),
        ),
    ]
