# Generated by Django 3.2.19 on 2023-06-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_alter_reservation_ordered_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.menu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ordered_items',
            field=models.ManyToManyField(blank=True, to='reservations.Item'),
        ),
    ]
