# Generated by Django 3.2.19 on 2023-06-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_auto_20230627_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationtable',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='reservations.reservation'),
        ),
    ]
