# Generated by Django 3.2.19 on 2023-06-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_reservationtable_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(blank=True, through='reservations.ReservationTable', to='reservations.Table'),
        ),
        migrations.AlterField(
            model_name='reservationtable',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
    ]
