# Generated by Django 3.2.19 on 2023-06-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_auto_20230628_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Default Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='Default phone_number', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(to='reservations.Table'),
        ),
    ]
