# Generated by Django 3.2.19 on 2023-06-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_auto_20230628_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Default Name', max_length=30),
        ),
    ]
