# Generated by Django 3.2.19 on 2023-06-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_auto_20230628_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
