# Generated by Django 3.2.19 on 2023-06-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_alter_reservation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
        migrations.DeleteModel(
            name='ReservationTable',
        ),
    ]
